export const TEAMS_2026 = [
  { id:"mexico", name:"Mexico", flag:"🇲🇽", group:"A" },
  { id:"south-korea", name:"South Korea", flag:"🇰🇷", group:"A" },
  { id:"south-africa", name:"South Africa", flag:"🇿🇦", group:"A" },
  { id:"czech-republic", name:"Czech Republic", flag:"🇨🇿", group:"A" },
  { id:"canada", name:"Canada", flag:"🇨🇦", group:"B" },
  { id:"switzerland", name:"Switzerland", flag:"🇨🇭", group:"B" },
  { id:"qatar", name:"Qatar", flag:"🇶🇦", group:"B" },
  { id:"bosnia", name:"Bosnia & Herzegovina", flag:"🇧🇦", group:"B" },
  { id:"brazil", name:"Brazil", flag:"🇧🇷", group:"C" },
  { id:"morocco", name:"Morocco", flag:"🇲🇦", group:"C" },
  { id:"scotland", name:"Scotland", flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿", group:"C" },
  { id:"haiti", name:"Haiti", flag:"🇭🇹", group:"C" },
  { id:"usa", name:"USA", flag:"🇺🇸", group:"D" },
  { id:"australia", name:"Australia", flag:"🇦🇺", group:"D" },
  { id:"paraguay", name:"Paraguay", flag:"🇵🇾", group:"D" },
  { id:"turkey", name:"Türkiye", flag:"🇹🇷", group:"D" },
  { id:"germany", name:"Germany", flag:"🇩🇪", group:"E" },
  { id:"ecuador", name:"Ecuador", flag:"🇪🇨", group:"E" },
  { id:"ivory-coast", name:"Ivory Coast", flag:"🇨🇮", group:"E" },
  { id:"curacao", name:"Curaçao", flag:"🇨🇼", group:"E" },
  { id:"netherlands", name:"Netherlands", flag:"🇳🇱", group:"F" },
  { id:"japan", name:"Japan", flag:"🇯🇵", group:"F" },
  { id:"sweden", name:"Sweden", flag:"🇸🇪", group:"F" },
  { id:"tunisia", name:"Tunisia", flag:"🇹🇳", group:"F" },
  { id:"belgium", name:"Belgium", flag:"🇧🇪", group:"G" },
  { id:"iran", name:"Iran", flag:"🇮🇷", group:"G" },
  { id:"egypt", name:"Egypt", flag:"🇪🇬", group:"G" },
  { id:"new-zealand", name:"New Zealand", flag:"🇳🇿", group:"G" },
  { id:"spain", name:"Spain", flag:"🇪🇸", group:"H" },
  { id:"uruguay", name:"Uruguay", flag:"🇺🇾", group:"H" },
  { id:"saudi-arabia", name:"Saudi Arabia", flag:"🇸🇦", group:"H" },
  { id:"cape-verde", name:"Cape Verde", flag:"🇨🇻", group:"H" },
  { id:"france", name:"France", flag:"🇫🇷", group:"I" },
  { id:"senegal", name:"Senegal", flag:"🇸🇳", group:"I" },
  { id:"norway", name:"Norway", flag:"🇳🇴", group:"I" },
  { id:"iraq", name:"Iraq", flag:"🇮🇶", group:"I" },
  { id:"argentina", name:"Argentina", flag:"🇦🇷", group:"J" },
  { id:"austria", name:"Austria", flag:"🇦🇹", group:"J" },
  { id:"algeria", name:"Algeria", flag:"🇩🇿", group:"J" },
  { id:"jordan", name:"Jordan", flag:"🇯🇴", group:"J" },
  { id:"portugal", name:"Portugal", flag:"🇵🇹", group:"K" },
  { id:"colombia", name:"Colombia", flag:"🇨🇴", group:"K" },
  { id:"uzbekistan", name:"Uzbekistan", flag:"🇺🇿", group:"K" },
  { id:"dr-congo", name:"DR Congo", flag:"🇨🇩", group:"K" },
  { id:"england", name:"England", flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", group:"L" },
  { id:"croatia", name:"Croatia", flag:"🇭🇷", group:"L" },
  { id:"panama", name:"Panama", flag:"🇵🇦", group:"L" },
  { id:"ghana", name:"Ghana", flag:"🇬🇭", group:"L" },
];

export const POINTS_SYSTEM = {
  groupWin: 3,
  groupDraw: 1,
  groupLoss: 0,
  roundOf32: 1,
  roundOf16: 2,
  quarterFinal: 3,
  semiFinal: 5,
  runnerUp: 7,
  winner: 10,
  award: 3,
};

export const TOURNAMENT_AWARDS = [
  { id:"goldenBoot", label:"Golden Boot", emoji:"👟", description:"Top scorer" },
  { id:"goldenBall", label:"Golden Ball", emoji:"🥇", description:"Best player" },
  { id:"goldenGlove", label:"Golden Glove", emoji:"🧤", description:"Best goalkeeper" },
  { id:"youngPlayer", label:"Young Player", emoji:"⭐", description:"Best young player" },
  { id:"fairPlay", label:"Fair Play", emoji:"🤝", description:"Fair play award" },
];

export const FIXTURES = [
  { id:"f1",  date:"2026-06-11", time:"20:00 BST", teamA:"mexico",        teamB:"south-africa",   stage:"Group A", venue:"Mexico City Stadium" },
  { id:"f2",  date:"2026-06-12", time:"03:00 BST", teamA:"south-korea",   teamB:"czech-republic", stage:"Group A", venue:"Estadio Guadalajara" },
  { id:"f3",  date:"2026-06-18", time:"17:00 BST", teamA:"czech-republic",teamB:"south-africa",   stage:"Group A", venue:"Atlanta Stadium" },
  { id:"f4",  date:"2026-06-19", time:"02:00 BST", teamA:"mexico",        teamB:"south-korea",    stage:"Group A", venue:"Estadio Guadalajara" },
  { id:"f5",  date:"2026-06-25", time:"02:00 BST", teamA:"czech-republic",teamB:"mexico",         stage:"Group A", venue:"Mexico City Stadium" },
  { id:"f6",  date:"2026-06-25", time:"02:00 BST", teamA:"south-africa",  teamB:"south-korea",    stage:"Group A", venue:"Estadio Monterrey" },
  { id:"f7",  date:"2026-06-12", time:"20:00 BST", teamA:"canada",        teamB:"bosnia",         stage:"Group B", venue:"Toronto Stadium" },
  { id:"f8",  date:"2026-06-13", time:"20:00 BST", teamA:"qatar",         teamB:"switzerland",    stage:"Group B", venue:"San Francisco Bay Area Stadium" },
  { id:"f9",  date:"2026-06-18", time:"20:00 BST", teamA:"switzerland",   teamB:"bosnia",         stage:"Group B", venue:"Los Angeles Stadium" },
  { id:"f10", date:"2026-06-18", time:"23:00 BST", teamA:"canada",        teamB:"qatar",          stage:"Group B", venue:"BC Place, Vancouver" },
  { id:"f11", date:"2026-06-24", time:"20:00 BST", teamA:"switzerland",   teamB:"canada",         stage:"Group B", venue:"BC Place, Vancouver" },
  { id:"f12", date:"2026-06-24", time:"20:00 BST", teamA:"bosnia",        teamB:"qatar",          stage:"Group B", venue:"Seattle Stadium" },
  { id:"f13", date:"2026-06-13", time:"23:00 BST", teamA:"brazil",        teamB:"morocco",        stage:"Group C", venue:"New York New Jersey Stadium" },
  { id:"f14", date:"2026-06-14", time:"02:00 BST", teamA:"haiti",         teamB:"scotland",       stage:"Group C", venue:"Boston Stadium" },
  { id:"f15", date:"2026-06-19", time:"23:00 BST", teamA:"scotland",      teamB:"morocco",        stage:"Group C", venue:"Boston Stadium" },
  { id:"f16", date:"2026-06-20", time:"02:00 BST", teamA:"brazil",        teamB:"haiti",          stage:"Group C", venue:"Philadelphia Stadium" },
  { id:"f17", date:"2026-06-24", time:"23:00 BST", teamA:"morocco",       teamB:"haiti",          stage:"Group C", venue:"Atlanta Stadium" },
  { id:"f18", date:"2026-06-24", time:"23:00 BST", teamA:"scotland",      teamB:"brazil",         stage:"Group C", venue:"Miami Stadium" },
  { id:"f19", date:"2026-06-13", time:"01:00 BST", teamA:"usa",           teamB:"paraguay",       stage:"Group D", venue:"Los Angeles Stadium" },
  { id:"f20", date:"2026-06-14", time:"05:00 BST", teamA:"australia",     teamB:"turkey",         stage:"Group D", venue:"BC Place, Vancouver" },
  { id:"f21", date:"2026-06-19", time:"20:00 BST", teamA:"usa",           teamB:"australia",      stage:"Group D", venue:"Seattle Stadium" },
  { id:"f22", date:"2026-06-20", time:"05:00 BST", teamA:"turkey",        teamB:"paraguay",       stage:"Group D", venue:"San Francisco Bay Area Stadium" },
  { id:"f23", date:"2026-06-26", time:"03:00 BST", teamA:"turkey",        teamB:"usa",            stage:"Group D", venue:"Los Angeles Stadium" },
  { id:"f24", date:"2026-06-26", time:"03:00 BST", teamA:"paraguay",      teamB:"australia",      stage:"Group D", venue:"San Francisco Bay Area Stadium" },
  { id:"f25", date:"2026-06-14", time:"18:00 BST", teamA:"germany",       teamB:"curacao",        stage:"Group E", venue:"Houston Stadium" },
  { id:"f26", date:"2026-06-15", time:"00:00 BST", teamA:"ivory-coast",   teamB:"ecuador",        stage:"Group E", venue:"Philadelphia Stadium" },
  { id:"f27", date:"2026-06-20", time:"21:00 BST", teamA:"germany",       teamB:"ivory-coast",    stage:"Group E", venue:"Toronto Stadium" },
  { id:"f28", date:"2026-06-21", time:"01:00 BST", teamA:"ecuador",       teamB:"curacao",        stage:"Group E", venue:"Kansas City Stadium" },
  { id:"f29", date:"2026-06-25", time:"21:00 BST", teamA:"curacao",       teamB:"ivory-coast",    stage:"Group E", venue:"Philadelphia Stadium" },
  { id:"f30", date:"2026-06-25", time:"21:00 BST", teamA:"ecuador",       teamB:"germany",        stage:"Group E", venue:"New York New Jersey Stadium" },
  { id:"f31", date:"2026-06-14", time:"21:00 BST", teamA:"netherlands",   teamB:"japan",          stage:"Group F", venue:"Dallas Stadium" },
  { id:"f32", date:"2026-06-15", time:"03:00 BST", teamA:"sweden",        teamB:"tunisia",        stage:"Group F", venue:"Estadio Monterrey" },
  { id:"f33", date:"2026-06-20", time:"18:00 BST", teamA:"netherlands",   teamB:"sweden",         stage:"Group F", venue:"Houston Stadium" },
  { id:"f34", date:"2026-06-21", time:"05:00 BST", teamA:"tunisia",       teamB:"japan",          stage:"Group F", venue:"Estadio Monterrey" },
  { id:"f35", date:"2026-06-26", time:"00:00 BST", teamA:"japan",         teamB:"sweden",         stage:"Group F", venue:"Dallas Stadium" },
  { id:"f36", date:"2026-06-26", time:"00:00 BST", teamA:"tunisia",       teamB:"netherlands",    stage:"Group F", venue:"Kansas City Stadium" },
  { id:"f37", date:"2026-06-15", time:"20:00 BST", teamA:"belgium",       teamB:"egypt",          stage:"Group G", venue:"Seattle Stadium" },
  { id:"f38", date:"2026-06-16", time:"02:00 BST", teamA:"iran",          teamB:"new-zealand",    stage:"Group G", venue:"Los Angeles Stadium" },
  { id:"f39", date:"2026-06-21", time:"20:00 BST", teamA:"belgium",       teamB:"iran",           stage:"Group G", venue:"Los Angeles Stadium" },
  { id:"f40", date:"2026-06-22", time:"02:00 BST", teamA:"new-zealand",   teamB:"egypt",          stage:"Group G", venue:"BC Place, Vancouver" },
  { id:"f41", date:"2026-06-27", time:"04:00 BST", teamA:"egypt",         teamB:"iran",           stage:"Group G", venue:"Seattle Stadium" },
  { id:"f42", date:"2026-06-27", time:"04:00 BST", teamA:"new-zealand",   teamB:"belgium",        stage:"Group G", venue:"BC Place, Vancouver" },
  { id:"f43", date:"2026-06-15", time:"17:00 BST", teamA:"spain",         teamB:"cape-verde",     stage:"Group H", venue:"Atlanta Stadium" },
  { id:"f44", date:"2026-06-15", time:"23:00 BST", teamA:"saudi-arabia",  teamB:"uruguay",        stage:"Group H", venue:"Miami Stadium" },
  { id:"f45", date:"2026-06-21", time:"17:00 BST", teamA:"spain",         teamB:"saudi-arabia",   stage:"Group H", venue:"Atlanta Stadium" },
  { id:"f46", date:"2026-06-21", time:"23:00 BST", teamA:"uruguay",       teamB:"cape-verde",     stage:"Group H", venue:"Miami Stadium" },
  { id:"f47", date:"2026-06-27", time:"01:00 BST", teamA:"cape-verde",    teamB:"saudi-arabia",   stage:"Group H", venue:"Houston Stadium" },
  { id:"f48", date:"2026-06-27", time:"01:00 BST", teamA:"uruguay",       teamB:"spain",          stage:"Group H", venue:"Estadio Guadalajara" },
  { id:"f49", date:"2026-06-16", time:"20:00 BST", teamA:"france",        teamB:"senegal",        stage:"Group I", venue:"New York New Jersey Stadium" },
  { id:"f50", date:"2026-06-16", time:"23:00 BST", teamA:"iraq",          teamB:"norway",         stage:"Group I", venue:"Boston Stadium" },
  { id:"f51", date:"2026-06-23", time:"01:00 BST", teamA:"norway",        teamB:"senegal",        stage:"Group I", venue:"Toronto Stadium" },
  { id:"f52", date:"2026-06-22", time:"22:00 BST", teamA:"france",        teamB:"iraq",           stage:"Group I", venue:"Philadelphia Stadium" },
  { id:"f53", date:"2026-06-26", time:"20:00 BST", teamA:"norway",        teamB:"france",         stage:"Group I", venue:"Boston Stadium" },
  { id:"f54", date:"2026-06-26", time:"20:00 BST", teamA:"senegal",       teamB:"iraq",           stage:"Group I", venue:"Toronto Stadium" },
  { id:"f55", date:"2026-06-17", time:"02:00 BST", teamA:"argentina",     teamB:"algeria",        stage:"Group J", venue:"Kansas City Stadium" },
  { id:"f56", date:"2026-06-17", time:"05:00 BST", teamA:"austria",       teamB:"jordan",         stage:"Group J", venue:"San Francisco Bay Area Stadium" },
  { id:"f57", date:"2026-06-22", time:"18:00 BST", teamA:"argentina",     teamB:"austria",        stage:"Group J", venue:"Dallas Stadium" },
  { id:"f58", date:"2026-06-23", time:"04:00 BST", teamA:"jordan",        teamB:"algeria",        stage:"Group J", venue:"San Francisco Bay Area Stadium" },
  { id:"f59", date:"2026-06-28", time:"03:00 BST", teamA:"algeria",       teamB:"austria",        stage:"Group J", venue:"Kansas City Stadium" },
  { id:"f60", date:"2026-06-28", time:"03:00 BST", teamA:"jordan",        teamB:"argentina",      stage:"Group J", venue:"Dallas Stadium" },
  { id:"f61", date:"2026-06-17", time:"18:00 BST", teamA:"portugal",      teamB:"dr-congo",       stage:"Group K", venue:"Houston Stadium" },
  { id:"f62", date:"2026-06-18", time:"03:00 BST", teamA:"uzbekistan",    teamB:"colombia",       stage:"Group K", venue:"Mexico City Stadium" },
  { id:"f63", date:"2026-06-23", time:"18:00 BST", teamA:"portugal",      teamB:"uzbekistan",     stage:"Group K", venue:"Houston Stadium" },
  { id:"f64", date:"2026-06-24", time:"03:00 BST", teamA:"colombia",      teamB:"dr-congo",       stage:"Group K", venue:"Estadio Guadalajara" },
  { id:"f65", date:"2026-06-28", time:"00:30 BST", teamA:"colombia",      teamB:"portugal",       stage:"Group K", venue:"Miami Stadium" },
  { id:"f66", date:"2026-06-28", time:"00:30 BST", teamA:"dr-congo",      teamB:"uzbekistan",     stage:"Group K", venue:"Atlanta Stadium" },
  { id:"f67", date:"2026-06-17", time:"21:00 BST", teamA:"england",       teamB:"croatia",        stage:"Group L", venue:"Dallas Stadium" },
  { id:"f68", date:"2026-06-18", time:"00:00 BST", teamA:"ghana",         teamB:"panama",         stage:"Group L", venue:"Toronto Stadium" },
  { id:"f69", date:"2026-06-23", time:"21:00 BST", teamA:"england",       teamB:"ghana",          stage:"Group L", venue:"Boston Stadium" },
  { id:"f70", date:"2026-06-24", time:"00:00 BST", teamA:"panama",        teamB:"croatia",        stage:"Group L", venue:"Boston Stadium" },
  { id:"f71", date:"2026-06-27", time:"22:00 BST", teamA:"panama",        teamB:"england",        stage:"Group L", venue:"New York New Jersey Stadium" },
  { id:"f72", date:"2026-06-27", time:"22:00 BST", teamA:"croatia",       teamB:"ghana",          stage:"Group L", venue:"Philadelphia Stadium" },
  { id:"r32-1",  date:"2026-06-28", time:"20:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 1",  venue:"Los Angeles Stadium" },
  { id:"r32-2",  date:"2026-06-29", time:"18:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 2",  venue:"Houston Stadium" },
  { id:"r32-3",  date:"2026-06-29", time:"21:30 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 3",  venue:"Boston Stadium" },
  { id:"r32-4",  date:"2026-06-30", time:"02:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 4",  venue:"Estadio Monterrey" },
  { id:"r32-5",  date:"2026-06-30", time:"18:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 5",  venue:"Dallas Stadium" },
  { id:"r32-6",  date:"2026-06-30", time:"22:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 6",  venue:"New York New Jersey Stadium" },
  { id:"r32-7",  date:"2026-07-01", time:"02:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 7",  venue:"Mexico City Stadium" },
  { id:"r32-8",  date:"2026-07-01", time:"17:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 8",  venue:"Atlanta Stadium" },
  { id:"r32-9",  date:"2026-07-01", time:"21:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 9",  venue:"Seattle Stadium" },
  { id:"r32-10", date:"2026-07-02", time:"01:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 10", venue:"San Francisco Bay Area Stadium" },
  { id:"r32-11", date:"2026-07-02", time:"20:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 11", venue:"Los Angeles Stadium" },
  { id:"r32-12", date:"2026-07-03", time:"00:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 12", venue:"Toronto Stadium" },
  { id:"r32-13", date:"2026-07-03", time:"04:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 13", venue:"BC Place, Vancouver" },
  { id:"r32-14", date:"2026-07-03", time:"19:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 14", venue:"Dallas Stadium" },
  { id:"r32-15", date:"2026-07-03", time:"23:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 15", venue:"Miami Stadium" },
  { id:"r32-16", date:"2026-07-04", time:"01:30 BST", teamA:"tba", teamB:"tba", stage:"Round of 32 - Match 16", venue:"BC Place, Vancouver" },
  { id:"r16-1", date:"2026-07-04", time:"18:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 16 - Match 1", venue:"Houston Stadium" },
  { id:"r16-2", date:"2026-07-04", time:"22:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 16 - Match 2", venue:"Philadelphia Stadium" },
  { id:"r16-3", date:"2026-07-05", time:"21:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 16 - Match 3", venue:"New York New Jersey Stadium" },
  { id:"r16-4", date:"2026-07-06", time:"01:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 16 - Match 4", venue:"Mexico City Stadium" },
  { id:"r16-5", date:"2026-07-06", time:"20:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 16 - Match 5", venue:"Dallas Stadium" },
  { id:"r16-6", date:"2026-07-07", time:"01:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 16 - Match 6", venue:"Seattle Stadium" },
  { id:"r16-7", date:"2026-07-07", time:"17:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 16 - Match 7", venue:"Atlanta Stadium" },
  { id:"r16-8", date:"2026-07-07", time:"21:00 BST", teamA:"tba", teamB:"tba", stage:"Round of 16 - Match 8", venue:"BC Place, Vancouver" },
  { id:"qf1", date:"2026-07-09", time:"21:00 BST", teamA:"tba", teamB:"tba", stage:"Quarter Final 1", venue:"Boston Stadium" },
  { id:"qf2", date:"2026-07-10", time:"20:00 BST", teamA:"tba", teamB:"tba", stage:"Quarter Final 2", venue:"Los Angeles Stadium" },
  { id:"qf3", date:"2026-07-11", time:"22:00 BST", teamA:"tba", teamB:"tba", stage:"Quarter Final 3", venue:"Miami Stadium" },
  { id:"qf4", date:"2026-07-12", time:"02:00 BST", teamA:"tba", teamB:"tba", stage:"Quarter Final 4", venue:"Kansas City Stadium" },
  { id:"sf1", date:"2026-07-14", time:"20:00 BST", teamA:"tba", teamB:"tba", stage:"Semi Final 1", venue:"Dallas Stadium" },
  { id:"sf2", date:"2026-07-15", time:"20:00 BST", teamA:"tba", teamB:"tba", stage:"Semi Final 2", venue:"Atlanta Stadium" },
  { id:"3rd", date:"2026-07-18", time:"22:00 BST", teamA:"tba", teamB:"tba", stage:"Third Place Play-off", venue:"Miami Stadium" },
  { id:"fin", date:"2026-07-19", time:"20:00 BST", teamA:"tba", teamB:"tba", stage:"🏆 Final", venue:"New York New Jersey Stadium" },
];