export const TEAMS_2026 = [
  { id:"mexico", name:"Mexico", flag:"🇲🇽", group:"A" },
  { id:"south-korea", name:"South Korea", flag:"🇰🇷", group:"A" },
  { id:"south-africa", name:"South Africa", flag:"🇿🇦", group:"A" },
  { id:"czech-republic", name:"Czech Republic", flag:"🇨🇿", group:"A" },
  { id:"canada", name:"Canada", flag:"🇨🇦", group:"B" },
  { id:"switzerland", name:"Switzerland", flag:"🇨🇭", group:"B" },
  { id:"qatar", name:"Qatar", flag:"🇶🇦", group:"B" },
  { id:"bosnia", name:"Bosnia & Herzegovina", flag:"🇧🇦", group:"B" },
  { id:"brazil", name:"Brazil", flag:"🇧🇷", group:"C" },
  { id:"morocco", name:"Morocco", flag:"🇲🇦", group:"C" },
  { id:"scotland", name:"Scotland", flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿", group:"C" },
  { id:"haiti", name:"Haiti", flag:"🇭🇹", group:"C" },
  { id:"usa", name:"USA", flag:"🇺🇸", group:"D" },
  { id:"australia", name:"Australia", flag:"🇦🇺", group:"D" },
  { id:"paraguay", name:"Paraguay", flag:"🇵🇾", group:"D" },
  { id:"turkey", name:"Türkiye", flag:"🇹🇷", group:"D" },
  { id:"germany", name:"Germany", flag:"🇩🇪", group:"E" },
  { id:"ecuador", name:"Ecuador", flag:"🇪🇨", group:"E" },
  { id:"ivory-coast", name:"Ivory Coast", flag:"🇨🇮", group:"E" },
  { id:"curacao", name:"Curaçao", flag:"🇨🇼", group:"E" },
  { id:"netherlands", name:"Netherlands", flag:"🇳🇱", group:"F" },
  { id:"japan", name:"Japan", flag:"🇯🇵", group:"F" },
  { id:"sweden", name:"Sweden", flag:"🇸🇪", group:"F" },
  { id:"tunisia", name:"Tunisia", flag:"🇹🇳", group:"F" },
  { id:"belgium", name:"Belgium", flag:"🇧🇪", group:"G" },
  { id:"iran", name:"Iran", flag:"🇮🇷", group:"G" },
  { id:"egypt", name:"Egypt", flag:"🇪🇬", group:"G" },
  { id:"new-zealand", name:"New Zealand", flag:"🇳🇿", group:"G" },
  { id:"spain", name:"Spain", flag:"🇪🇸", group:"H" },
  { id:"uruguay", name:"Uruguay", flag:"🇺🇾", group:"H" },
  { id:"saudi-arabia", name:"Saudi Arabia", flag:"🇸🇦", group:"H" },
  { id:"cape-verde", name:"Cape Verde", flag:"🇨🇻", group:"H" },
  { id:"france", name:"France", flag:"🇫🇷", group:"I" },
  { id:"senegal", name:"Senegal", flag:"🇸🇳", group:"I" },
  { id:"norway", name:"Norway", flag:"🇳🇴", group:"I" },
  { id:"iraq", name:"Iraq", flag:"🇮🇶", group:"I" },
  { id:"argentina", name:"Argentina", flag:"🇦🇷", group:"J" }